//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poster()
        {
            this.Användare2 = new HashSet<Användare>();
        }
    
        public int PostID { get; set; }
        public Nullable<int> PostAv { get; set; }
        public Nullable<int> PostTill { get; set; }
        public string Meddelande { get; set; }
    
        public virtual Användare Användare { get; set; }
        public virtual Användare Användare1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Användare> Användare2 { get; set; }
    }
}
